version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      java: corretto8
    commands:
      - npm install -g sonarqube-scanner
      - cd devawsfrontend
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - npm run coverage
  post_build:
    commands:
      - echo Build completed on `date`
      - npm run sonar
artifacts:
  files:
    - '**/java-hello-world.war'
    - 'appspec.yml'
    - 'install.sh'
  discard-paths: yes  
