version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      java: 11
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:./sonar-scanner-3.3.0.1492-linux/bin/  
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - sonar-scanner -Dsonar.organization=aswanth-asokan -Dsonar.projectKey=sampleone -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=7f69a357e3bd5555b9dc7a5590238d28febbd5b4
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=sampleone > analysis.json
      - cat analysis.json
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/java-hello-world.war'
    - 'appspec.yml'
    - 'install.sh'
  discard-paths: yes  
    
